# Site settings
baseURL = "https://aakshintala.com"
languageCode = "en-US"
title = "Amogh Akshintala"
theme = "minimal-dark"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]
pluralizelisttitles = "false"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-121294168-1"

# Copyright
copyright = "&copy;{year} Amogh Akshintala"

[params]

  # Metadata for search engines and social sharing
  author = "Amogh Akshintala"
  description = "Amogh Akshintala's web presence..."
  shareImage = "images/social.jpg"
  twitterHandle = "aakshintala"

  # Favicon
  favicon = "images/favicon.ico"

  # Links List #1
  [[params.nav]]

      [[params.nav.link]]
        text = "Blog"
        url = "/blog"

      [[params.nav.link]]
        text = "Publications"
        url = "/publications"

      [[params.nav.link]]
        text = "Resume"
        url = "/resume"

  [permalinks]
    blog = "/blog/:slug"
